openapi: 3.1.0
info:
  version: "1"
  title: api
paths:
  test:
    put:
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
